name: build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
        java-version: [11]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test run
      run: make test
